### PR TITLE
Improve code coverage

### PR DESCRIPTION
**Pull request by janniklasrose**
First attempt at solving some of the issues in #12

### CODE REVIEW

**Comment by markrichardson** [comment]
nice work. I suspected something like this was the cause of the de-facto 90% ceiling on test coverage but didn't know about the exclude_lines protocol ...

do you have any idea how to fix the code climate "test coverage" badge at the top of the landing page https://github.com/chebpy/chebp by any chance?

**Comment by janniklasrose** [comment]
> code climate "test coverage" badge

Do you mean the [Coverage Status](https://coveralls.io/github/chebpy/chebpy?branch=master) badge? It seems stuck on 91% but on [coveralls.io](https://coveralls.io/github/chebpy/chebpy) it is at 96% now. Must be a GitHub issue, using some cached version?

Compare to just visiting the badge URL `https://coveralls.io/repos/github/chebpy/chebpy/badge.svg?branch=master` in your browser, which redirects to this:

Badge

**Comment by janniklasrose** [comment]
> Must be a GitHub issue, using some cached version?

Scratch that, it's a browser issue. Used a different device and it shows the correct badge.

**Comment by markrichardson** [comment]
So the _coveralls_ "coverage" badge that I manually embedded into README.MD is lining OK (up to the 91% vs 96% refresh)

image

But the _code climate_ "test coverage" badge is blanked out (I didn't add this ... it must be something that GitHub does for you):

image

Do you see this or is it just me?

**Comment by janniklasrose** [comment]
ooh, I don't see either of those badges in the header. This must be a GitHub thing, since you have linked the project to codeclimate? On codeclimate itself the _test coverage_ section is also empty, hence #17?

**Pull request merged**
