### PR TITLE
Replaced deprecated np.float with float

### PR DESCRIPTION
**Pull request by Mark2000**
Addressing issue #68

### CODE REVIEW

**Comment by Mark2000** [comment]
@nbren12 I see that there hasn't been any activity on this repo for a while, and looks like you're the only maintainer who's very active on GitHub these days. Using it in my research for the next few year and would be happy to jump onboard as a maintainer. Could even try to get the package up on PyPI, since all that's there currently is a very stale Python 2 version.

**Comment by markrichardson** [comment]
hi @Mark2000 I'm the author and primary maintainer on this repo at present. Would be great if you wanted to get involved. How did you want to proceed?

**Comment by Mark2000** [comment]
I’d be down to keep an eye on and address general upkeep/quality of life issues as they arise (though don’t know anything about the math of Chebychev polynomials). Let me know if there’s anything beyond standard open source practices this repo follows.

**Comment by markrichardson** [comment]
all fairly standard I think... good to have you on board! let me know if I can help

**Comment by Mark2000** [comment]
@markrichardson bumping this ^

**Comment by markrichardson** [comment]
sorry for delay @Mark2000, should be good now?

**Pull request merged**
