### PR TITLE
Refactoring & Housekeeping

### PR DESCRIPTION
**Pull request by janniklasrose**
I've done some tidying up of the source code, including removal of py2 relics. All changes should be pretty self-explanatory, otherwise the extended commit messages might clear things up.

## Preferences

I also refactored the `chebpy.core.settings` module, hopefully for the better. It now supports a context manager:
```python
from chebpy import UserPreferences  # alias for chebpy.core.settings.ChebPreferences

cheb_strict = chebfun(my_function)
with UserPreferences() as prefs:
    prefs.eps = 1e-6  # relaxed tolerances
    cheb_relaxed = chebfun(my_function)
```

### CODE REVIEW

**Comment by markrichardson** [comment]
Makes sense, will hold up

**Comment by janniklasrose** [comment]
e85ce3b seems to have done it: I've removed the `@abstractmethod`s for `plot` and `plotcoeff` from the `ABC`s, since this is an optional runtime environment--dependent feature.

At the same time I've updated the tests to use `@unittest.skipIf` for all `Plotting` test classes based on the presence of the `plt` (=`matplotlib.pyplot`) module. This way it now prints SKIP instead of OK for those tests in the "noplot" part of the test matrix.

**Comment by janniklasrose** [comment]
Still need to update the coveralls action here to support [parallel (matrix) testing](https://github.com/coverallsapp/github-action/#complete-parallel-job-example). I'll let you know when it's ready to merge

**Comment by janniklasrose** [comment]
Ready to merge - all checks passing except codeclimate (which is expected due to the refactoring from `chebpy.core.ui` to `chebpy.api`).

**Comment by markrichardson** [comment]
Good stuff, merging now

**Pull request merged**
